import type { PipelineRunResult } from './demoSchema';

const steps = [
  'User Input',
  'Scenario Module',
  'WorldSpec + Harness',
  'Evidence Module',
  'Assumption Module',
  'Compiler Module',
  'Simulation Runtime',
  'Agent Module',
  'Trace Module',
  'Report Module',
  'Frontend Visualization',
  'Vector Search',
];

export const samplePipelineResult: PipelineRunResult = {
  question:
    'If high schools replace exams with AI-assisted project-based assessment, what happens?',
  pipelineSteps: steps.map((name, index) => ({
    id: index + 1,
    name,
    status: 'done',
  })),
  compiledState: {
    tick: 1,
    status: 'visualized',
    zones: [
      {
        id: 'classroom',
        name: 'Classroom',
        purpose: 'Students and teachers experience day-to-day assessment changes.',
        x: 120,
        y: 120,
        width: 190,
        height: 130,
        color: 0x8fbf6f,
      },
      {
        id: 'teacher-office',
        name: 'Teacher Office',
        purpose: 'Teachers discuss grading workload, rubric design, and cheating risk.',
        x: 390,
        y: 95,
        width: 190,
        height: 125,
        color: 0xb98a5c,
      },
      {
        id: 'principal-office',
        name: 'Principal Office',
        purpose: 'School leadership balances fairness, public trust, and operations.',
        x: 645,
        y: 145,
        width: 210,
        height: 130,
        color: 0x8a8ec7,
      },
      {
        id: 'admissions-office',
        name: 'Admissions Office',
        purpose: 'University evaluators test whether project artifacts are comparable.',
        x: 635,
        y: 390,
        width: 230,
        height: 140,
        color: 0x739ec8,
      },
      {
        id: 'tutoring-street',
        name: 'Tutoring Street',
        purpose: 'Private tutoring providers adapt to project-based evaluation.',
        x: 185,
        y: 395,
        width: 230,
        height: 145,
        color: 0xc49a54,
      },
    ],
    agents: [
      {
        id: 'student',
        name: 'Student',
        role: 'High school student',
        goal: 'Gain fair recognition for learning and avoid being disadvantaged.',
        concerns: ['unequal family support', 'unclear grading standards'],
        zoneId: 'classroom',
        x: 185,
        y: 185,
        spriteRow: 0,
        state: { satisfaction: 48, trust: 46, stress: 43, influence: 45 },
      },
      {
        id: 'parent',
        name: 'Parent',
        role: 'Family decision-maker',
        goal: 'Protect the child from unfair evaluation and admissions uncertainty.',
        concerns: ['project authenticity', 'extra cost'],
        zoneId: 'classroom',
        x: 245,
        y: 195,
        spriteRow: 1,
        state: { satisfaction: 48, trust: 46, stress: 47, influence: 50 },
      },
      {
        id: 'teacher',
        name: 'Teacher',
        role: 'Assessment designer and grader',
        goal: 'Evaluate learning fairly without unsustainable workload.',
        concerns: ['rubric reliability', 'feedback burden'],
        zoneId: 'teacher-office',
        x: 470,
        y: 160,
        spriteRow: 2,
        state: { satisfaction: 48, trust: 48, stress: 51, influence: 55 },
      },
      {
        id: 'principal',
        name: 'Principal',
        role: 'School administrator',
        goal: 'Implement reform while maintaining trust and measurable outcomes.',
        concerns: ['policy risk', 'teacher capacity'],
        zoneId: 'principal-office',
        x: 735,
        y: 210,
        spriteRow: 3,
        state: { satisfaction: 48, trust: 48, stress: 55, influence: 60 },
      },
      {
        id: 'admissions-officer',
        name: 'Admissions Officer',
        role: 'University evaluator',
        goal: 'Compare applicants using reliable and interpretable signals.',
        concerns: ['cross-school comparability', 'authenticity'],
        zoneId: 'admissions-office',
        x: 745,
        y: 455,
        spriteRow: 4,
        state: { satisfaction: 48, trust: 46, stress: 59, influence: 65 },
      },
      {
        id: 'tutoring-owner',
        name: 'Tutoring Owner',
        role: 'Private education provider',
        goal: 'Adapt services to the new evaluation system.',
        concerns: ['new market demand', 'gaming behavior'],
        zoneId: 'tutoring-street',
        x: 295,
        y: 470,
        spriteRow: 5,
        state: { satisfaction: 48, trust: 53, stress: 63, influence: 70 },
      },
    ],
    metrics: [
      { id: 'fairness', name: 'Fairness', value: 43, direction: 'increase_good' },
      { id: 'workload', name: 'Teacher workload', value: 56, direction: 'decrease_good' },
      { id: 'admissions-trust', name: 'Admissions trust', value: 43, direction: 'increase_good' },
      { id: 'gaming-risk', name: 'Gaming risk', value: 52, direction: 'decrease_good' },
    ],
  },
  agentDecisions: [
    {
      id: 'AD-student',
      agentId: 'student',
      observation:
        'Student sees project assessment replacing exams and worries that family resources change project quality.',
      retrievedEvidenceIds: ['EV2'],
      retrievedAssumptionIds: ['A2'],
      proposedAction: {
        type: 'request_fairness_guarantee',
        targetIds: ['replace-exams', 'fairness'],
        metricEffects: { fairness: -2 },
      },
      reason:
        'The student asks for fairness guarantees because unequal support can make project artifacts less comparable.',
      confidence: 'medium',
    },
    {
      id: 'AD-teacher',
      agentId: 'teacher',
      observation:
        'Teacher sees open-ended assessment and expects rubric design and feedback load to increase.',
      retrievedEvidenceIds: ['EV3'],
      retrievedAssumptionIds: ['A3'],
      proposedAction: {
        type: 'raise_workload_concern',
        targetIds: ['replace-exams', 'workload'],
        metricEffects: { workload: 3 },
      },
      reason:
        'The teacher raises workload risk because project assessment requires more feedback and moderation.',
      confidence: 'high',
    },
    {
      id: 'AD-admissions',
      agentId: 'admissions-officer',
      observation:
        'Admissions officer needs comparable signals across schools but sees project portfolios becoming central.',
      retrievedEvidenceIds: ['EV1'],
      retrievedAssumptionIds: ['A1'],
      proposedAction: {
        type: 'challenge_signal_comparability',
        targetIds: ['replace-exams', 'admissions-trust'],
        metricEffects: { 'admissions-trust': -3 },
      },
      reason:
        'The admissions officer challenges comparability because portfolios are harder to normalize across schools.',
      confidence: 'high',
    },
  ],
  traceEvents: [
    {
      id: 'TE-student-1',
      tick: 1,
      actorId: 'student',
      actionType: 'request_fairness_guarantee',
      reason:
        'Student reacts to unequal family support risk before accepting the reform as fair.',
      evidenceIds: ['EV2'],
      assumptionIds: ['A2'],
      metricDeltas: { fairness: -2, 'gaming-risk': 1 },
    },
    {
      id: 'TE-teacher-1',
      tick: 1,
      actorId: 'teacher',
      actionType: 'raise_workload_concern',
      reason:
        'Teacher flags the grading and feedback burden created by open-ended projects.',
      evidenceIds: ['EV3'],
      assumptionIds: ['A3'],
      metricDeltas: { workload: 3, fairness: 1 },
    },
    {
      id: 'TE-admissions-1',
      tick: 1,
      actorId: 'admissions-officer',
      actionType: 'challenge_signal_comparability',
      reason:
        'Admissions officer reduces trust because project outputs are less comparable than standardized exams.',
      evidenceIds: ['EV1'],
      assumptionIds: ['A1'],
      metricDeltas: { 'admissions-trust': -3, fairness: -1 },
    },
  ],
  reportClaims: [
    {
      id: 'RC1',
      text:
        'Replacing exams with AI-assisted projects creates a fairness risk unless schools add comparable rubrics and support.',
      confidence: 'medium',
      evidenceIds: ['EV2'],
      assumptionIds: ['A2'],
      traceEventIds: ['TE-student-1'],
    },
    {
      id: 'RC2',
      text:
        'Teacher workload is likely to rise before tooling and moderation processes mature.',
      confidence: 'high',
      evidenceIds: ['EV3'],
      assumptionIds: ['A3'],
      traceEventIds: ['TE-teacher-1'],
    },
  ],
  retrievalResults: [
    {
      id: 'EV1',
      kind: 'evidence',
      title: 'Comparable admissions signals',
      text: 'Admissions systems prefer comparable signals when evaluating applicants across schools.',
      score: 0.92,
    },
    {
      id: 'EV2',
      kind: 'evidence',
      title: 'Resource differences',
      text: 'Resource differences shape student access to enrichment and project support.',
      score: 0.88,
    },
    {
      id: 'A3',
      kind: 'assumption',
      title: 'Teacher workload',
      text: 'Teacher workload rises unless rubrics and AI feedback tools are carefully designed.',
      score: 0.81,
    },
  ],
};
